### PR TITLE
Add circleci build config.

### PR DESCRIPTION
**Pull request by david-martin**
* runs `test` npm script
* can build & publish container image when repo is tagged

A number of minor eslint errors are fixed to get that part of the build passing.

### CODE REVIEW

**Comment by david-martin** [comment]
@priley86 @dlabaj thoughts on the failing test? 

```
 FAIL  src/pages/tutorial/__tests__/tutorial.test.js (14.947s)
  ● TutorialPage Component › should render the TutorialPage component fulfilled state
```

**Comment by david-martin** [comment]
@priley86 @dlabaj
I've ran the below command to update the snapshot.
Does the updated snapshot look correct to you?

```
./node_modules/.bin/react-scripts test --env=jsdom --coverage --updateSnapshot
```

**Comment by priley86** [comment]
@david-martin this is looking very good to me, and yes that command will update the jest snapshots (you can also run `yarn test -u` as a shorthand). 

@dlabaj any additional thoughts?

I'm happy to see it merge when you are ready.

**Comment by david-martin** [comment]
I'd like to fix the docker push part of the ci build, and restrict that to only build and push an image for release tags.
I'll ping once added.

**Comment by priley86** [comment]
@david-martin would you mind letting us know what remote url to track once the CI is in place? When we merge PR's in the future, it would be nice to just point our UX/Design folks at your deployed location.

**Comment by david-martin** [comment]
> would you mind letting us know what remote url to track once the CI is in place

@priley86 Yes, definitely. Auto deploying to a cluster on merge to master is outside the scope of this PR, but is definitely on the radar.

This PR is good to merge from my point of view.
I've added content to the README about releasing.
This PR puts the first piece of the puzzle in place i.e. the image to run in OpenShift.

Next change/PR will be adding a template to use a built image from quay.io

**Comment by priley86** [comment]
hey @david-martin, i don't have any concerns at this time. I imagine there may be some future requests around auto deploying the app once the image is solidified. It might be nice to be able to test with customers/end users in a "staging" environment of sorts. Maybe you can consider this with future PRs and we can discuss further later.

@dlabaj any additional thoughts on this one?

**Pull request merged**
