### PR TITLE
INTLY-1159: Implement dashboard organization designs

### PR DESCRIPTION
**Pull request by mfrances17**
## Motivation
https://issues.jboss.org/browse/INTLY-1159

## What

- Categorize and group walkthroughs by repository, adding each repository's walkthroughs in their own group under a specific heading. The category heading is based off the 'pretty name' defined in the repository's walkthrough-config.json file. If the json file does not exist, use the last part of the github repo's name followed by 'Solution Patterns'. For example, in the first screen shot below, the json file for the above set of walkthroughs contained a pretty name of 'Red Hat Solution Patterns'. In the below set of walkthroughs, there was no json file in the 'https://github.com/integr8ly/example-customisations' repo, so the category was named 'example-customisations Solution Patterns'.
- Create a sort in which each category of walkthroughs is first sorted by the % completed, then alphabetically.

## Why
To work with new dashboard design.

## Verification Steps
1. Go on a Integreatly cluster that is running multiple repos and use my docker image for the web app:
         docker.io/mfrances17/dev-tutorial-web-app:latest
2. Verify that all walkthroughs are grouped and categorized by heading that corresponds to the json file/repo for which they belong. 
3. Verify that all unstarted walkthroughs are listed alphabetically under each category. 
4. Start a few of the walkthroughs and return to the home page to verify that the cards are now sorted by % completed, then alphabetically.

## Checklist:
- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Progress
- [x] Finished task

## Additional Notes
Link to demo (my demo starts 43 seconds in):
https://bluejeans.com/s/t3sRS/

**Screen cap: Categorized walkthroughs:**
categories

**Screen cap: Sorted after one walkthrough started:**
sorted

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@pb82 would you be able to review?

**Comment by jasonmadigan** [comment]
@aidenkeating one for you to take a look at (or Peter!)

**Comment by pb82** [comment]
@jasonmadigan sure, will have a look

**Comment by pb82** [comment]
👀

**Pull request merged**
