### PR TITLE
Update numbering

### PR DESCRIPTION
**Pull request by finp**
* manually add numbering to adoc files
* make all step headings visible

### CODE REVIEW

**Comment by mfrances17** [comment]
Looks good so far. For the interim solution, we'll want to get the resulting output files in as part of this PR otherwise it's not worth pushing up.

**Comment by finp** [comment]
@mfrances17 
I rebased on https://github.com/integr8ly/tutorial-web-app/tree/fixBottomNumbering to test this,
and noticed a problem navigating thru WT 1A, clicking 'Next' doesn't work, but I could set the URL manually to make the app work

**Comment by finp** [comment]
@mfrances17 
I rebased on https://github.com/integr8ly/tutorial-web-app/tree/fixBottomNumbering to test this,
and noticed a problem navigating thru WT 1A, clicking 'Next' doesn't work, but I could set the URL manually to make the app work

**Comment by mfrances17** [comment]
> @mfrances17
> I rebased on https://github.com/integr8ly/tutorial-web-app/tree/fixBottomNumbering to test this,
> and noticed a problem navigating thru WT 1A, clicking 'Next' doesn't work, but I could set the URL manually to make the app work

Wondering if the naming convention (introducing the period in the filename instead of dash) you used for the 1A adocs might have been the culprit. I see that you just renamed them, if that doesn't fix it, we can log a defect and investigate.

**Pull request merged**
