### PR TITLE
WIP: add instructions to custom walkthrough example

### PR DESCRIPTION
**Pull request by finp**
## Motivation
Custom walkthroughs contain a lot of i8 specific syntax, that needs to be explained
## What
add samples with callouts to explain syntax

## Progress

- [x] draft callout wt
- [x] split into small samples
- [x] overview sample
- [ ] task resources sample
- [ ] walkthrough resources and attributes
- [ ] verfications - fails, and numbering
- [ ] using sectnums

### CODE REVIEW

**Comment by finp** [comment]
@pb82 I added a custom resource, but didn't do it 'properly', could you add and write up how to?

(in new walkthrough, I tried to add 'asciidoc' links to act as walkthrough resource)

**Comment by pb82** [comment]
@finp Was it a rendering problem or did the resource not show up? `[type=walkthroughResource]` will only work in the preamble. It's ignored if you put it inside a task. Could that be the problem? `[type=taskResource]` can be used in tasks. The idea is that a `walkthroughResource` is a global resources that will be added to every task.

**Comment by pb82** [comment]
@finp i'll add this to your document

**Comment by finp** [comment]
closed in favor of https://github.com/integr8ly/example-customisations/pull/9

**Pull request closed without merging**
