### PR TITLE
Remove unused public/walkthroughs dir

### PR DESCRIPTION
**Pull request by aidenkeating**
The `public/walkthroughs` repo is no longer used. So it can be removed.

# Verification steps
* Ensure running the web app still works

### CODE REVIEW

**Comment by aidenkeating** [comment]
@david-martin @pb82 Mind taking a look?

**Comment by david-martin** [comment]
@aidenkeating I can give this a spin in my cluster if you rebase and have an image built

**Comment by aidenkeating** [comment]
@david-martin Rebased and pushed an image: `quay.io/aidenkeating/tutorial-web-app:remove-public-walkthroughs`.

**Comment by david-martin** [comment]
Merging as changes have landed for using a git repo for walkthroughs.
In the installer here: https://github.com/integr8ly/installation/pull/240/files
and operator here: https://github.com/integr8ly/tutorial-web-app-operator/pull/14/files

**Pull request merged**
