### PR TITLE
Temporary Walkthrough Sorting

### PR DESCRIPTION
**Pull request by evanshortiss**
## Motivation
Currently if a set of ordered walkthroughs are added they load in random order. It would be nice if a simple sort was performed to get them in numbered order based on the folder name, while we figure out a more complex/controlled sorting this would do.

## What
Added a sorter function to the tutorials dashboard component.

## Why
Without it walkthrough order is random. 

## How
Sorting is based on the ID plus overall title. This results in the ability to order walkthroughs. For example, the walkthroughs [here](https://github.com/RedHatWorkshops/dayinthelife-integration/tree/V2/docs/labs/citizen-integrator-track) will render correctly ordered with this change like so:

screenshot 2019-02-11 at 2 51 52 pm

## Verification Steps
1. Run the walkthrough using this command:

```
WALKTHROUGH_LOCATIONS="https://github.com/RedHatWorkshops/dayinthelife-integration?walkthroughsFolder=docs/labs/citizen-integrator-track/#V2,https://github.com/integr8ly/tutorial-web-app-walkthroughs" yarn start:dev
```

2. Verify order of labs is correct.

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

## Progress

- [x] Finished task
- [ ] TODO

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@evanshortiss UXD is currently designing and testing versions of the Dashboard with various sorting / filtering capabilities. I believe it would be best to hold off on changing the display methodology of the Dashboard items until these designs have been completed. 

You can find existing UXD stories in the tutorial-webapp Jira board, if you'd like to see what is upcoming.

**Comment by evanshortiss** [comment]
@mindreeper2420, yeah saw them, they look great 👍

We can use this branch in the meantime either way, thanks!

**Comment by finp** [comment]
@evanshortiss  does this work given the fact that walkthrough ids for 'developer' and 'integrator' DIL workshops are often the same, eg 'lab01' ? (maybe the workaround DIL have in place for directory layout compensates for this?)

**Comment by evanshortiss** [comment]
@finp good point, and actually I think it could be a wider problem...what happens if they try to include the repo twice!? Tested here and you can't actually include the repo twice so, there's larger complication here.

**Comment by finp** [comment]
@evanshortiss  I created https://issues.jboss.org/browse/INTLY-948 to capture what I think needs to happen as a first step. 
The good news is that I just tested using symlinks and that works, so anyone can use the dir structure they want as long as there's a symlink from that to `walkthroughs/<unique-id>` in their repo. That seems to me to be the best temp solution, WDYT?

**Comment by evanshortiss** [comment]
@finp not sure I follow that. Do you mean if they are using a custom directory structure locally? I think locally it already works using whatever structure you want if you pass it in the `WALKTHROUGHS_LOCATION` variable?

I addressed your previous comment in #402

**Comment by finp** [comment]
@evanshortiss I'm saying that this works https://github.com/RedHatWorkshops/dayinthelife-integration/pull/265/files
Throw this branch at web app and it just works, doesn't require any change in existing workflow, and will sort well on splash page with 'id' sorting

**Comment by evanshortiss** [comment]
@finp gtocha, I've been testing with that 👍 I agree though, a symlink works perfectly until we can get agreement and a merge on that PR

Both of these examples work assuming V2 branch is checked out in the DIL directory, and you checkout `walkthrough-git-custom-location` from my PR #402 :

```
WALKTHROUGH_LOCATIONS='/Users/eshortis/workspaces/work/integreatly/dayinthelife-integration/docs/labs/citizen-integrator-track,/Users/eshortis/workspaces/work/integreatly/dayinthelife-integration/docs/labs/developer-track' yarn start:dev
```

and

```
WALKTHROUGH_LOCATIONS="https://github.com/RedHatWorkshops/dayinthelife-integration?walkthroughsFolder=docs/labs/citizen-integrator-track&walkthroughsFolder=docs/labs/developer-track/#V2,/Users/eshortis/workspaces/work/integreatly/tutorial-web-app-walkthroughs/walkthroughs" yarn start:dev
```

**Comment by finp** [comment]
@evanshortiss I haven't tested it, so could be wrong, but looks like if you set walkthroughsFolder as above then lab01 from developer and citizen tracks would be displayed together, and that's not what we want, right?

**Comment by evanshortiss** [comment]
@finp nope, they get displayed correctly as unique items on the dashboard, and can be viewed also. Essentially, the ID conflict is resolved.

**Comment by finp** [comment]
Grand, sorry for I got the wrong end of the proverbial

**Comment by aidenkeating** [comment]
@evanshortiss I can try this out tomorrow. If we could bundle all the changes into a single commit that may be best so they can be reverted easily (if needed) when the changes mentioned in https://github.com/integr8ly/tutorial-web-app/pull/403#issuecomment-462534817 are made? 

@mindreeper2420 Are we fine with having these changes merged in the short-term until the full sorting changes are made?

@finp Are you aware if we have to ensure/maintain any specific order for the default Integreatly walkthroughs?

**Comment by finp** [comment]
@aidenkeating  I'm not aware of any requirement, but IMO the sorting should be 1,2,Publishing, and this PR implements that, right?

**Comment by aidenkeating** [comment]
@finp It does

## With numbered labs
Screen Shot 2019-03-15 at 10 29 25

# With default Integreatly walkthroughs
Screen Shot 2019-03-15 at 10 22 47

**Pull request merged**
