### PR TITLE
enable travis for pull requests to master

### PR DESCRIPTION
**Pull request by pb82**
For some reason travis builds are not triggered for PRs. Trying to enable them.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
Is there a specific need for it to build with Travis? I'm not sure I understand the benefit to having Travis with this, at the moment.

**Comment by pb82** [comment]
@mindreeper2420 It runs the tests for every pull request and we can see the status in Github. So if e.g. someone forgets to update the snapshots this would catch it.

**Comment by mindreeper2420** [comment]
Ok, sounds good. That'd be a great thing to have in the PRs.

**Comment by pb82** [comment]
@mindreeper2420 Automatic tests should be working now. You can see the details by clicking on `Show all checks -> Details`. I also added the yarn.lock file to the repo as suggested here: https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control

Does that look ok to you?

**Comment by dlabaj** [comment]
@pb82 @mindreeper2420 We removed it because we where having issues on the build environments they kept getting a permission error.  If that's fix then we should go ahead and add it back.

**Comment by dlabaj** [comment]
@pb82 It was an openshift issue we where seeing when trying to build the application.  It was fixed in this PR https://github.com/integr8ly/tutorial-web-app/pull/67 .  It should be fine to check it in now.

**Pull request merged**
