### PR TITLE
External wt git rebase

### PR DESCRIPTION
**Pull request by aidenkeating**
Rebase of #321 with a change to allow easier overrides of WALKTHROUGH_LOCATIONS (
c64b73b).

A separate task has been created to allow tags/branches to be specified.

### CODE REVIEW

**Comment by aidenkeating** [comment]
Related to: https://github.com/integr8ly/installation/pull/240
Related to: https://github.com/integr8ly/tutorial-web-app-operator/pull/14

@david-martin @pb82 @odra Would you mind taking a look? This is mainly just a rebase of #321. It required an operator and installer change too. I have PRs for those changes and custom images for verification.

This is the command I ran to test (using `aidenkeating:add-walkthrough-locations-env` branch of the installer).

```
ansible-playbook -i inventories/hosts.template playbooks/install.yml -e github_client_id=<id> -e github_client_secret=<secret>-e webapp_operator_image_url=docker.io/aidenkeatingrht/tutorial-web-app-operator -e webapp_operator_image_tag=dev -e webapp_image_url=docker.io/aidenkeatingrht/tutorial-web-app -e webapp_image_tag=dev
```

What we should see at the end is a web app that has the `WALKTHROUGH_LOCATIONS` env set correctly and the logs of it saying it's pulling from a repo.

It's deployed on the `akeating-592e` cluster.

**Comment by pb82** [comment]
👀

**Comment by david-martin** [comment]
also :eyes:

**Comment by david-martin** [comment]
Env var set as expected
```
oc set env dc/tutorial-web-app -n webapp --list | grep WALKTHROUGH_LOCATIONS
WALKTHROUGH_LOCATIONS=https://github.com/integr8ly/tutorial-web-app-walkthroughs.git
```

Git clone on startup seems to be working as expected

```
npm info it worked if it ends with ok
--
  | npm info using npm@6.4.1
  | npm info using node@v10.11.0
  | npm info lifecycle integreatly-web-app@2.0.0~prestart: integreatly-web-app@2.0.0
  | npm info lifecycle integreatly-web-app@2.0.0~start: integreatly-web-app@2.0.0
  |  
  | > integreatly-web-app@2.0.0 start /opt/app-root/src
  | > node server.js
  |  
  | Importing walkthrough from git https://github.com/integr8ly/tutorial-web-app-walkthroughs.git
  | asciidoctor: WARNING: <stdin>: line 44: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 49: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 54: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 43: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 48: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 53: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 36: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 42: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 48: section title out of sequence: expected level 1, got level 2
  | asciidoctor: WARNING: <stdin>: line 54: section title out of sequence: expected level 1, got level 2
  | Listening on port 5001
  | Failed to read extra configuration file: Error: ENOENT: no such file or directory, open '/etc/webapp/customServerConfig.json'
```

3 walkthroughs show up as expected
image

**Pull request merged**
