### PR TITLE
INTLY-1202 Update product info

### PR DESCRIPTION
**Pull request by aidenkeating**
* AMQ Online is now GA
* CodeReady should be Red Hat CodeReady Workspaces

Verification:
- Run `yarn start:dev` locally or against a cluster
- Ensure AMQ Online has no `preview` tag beside it
- Ensure the CodeReady service name is updated`

### CODE REVIEW

**Comment by aidenkeating** [comment]
## Running in local dev mode
screen shot 2019-03-04 at 10 31 54

## Running against a cluster
screen shot 2019-03-04 at 10 40 43
screen shot 2019-03-04 at 10 42 58

**Comment by aidenkeating** [comment]
@maleck13 Mind taking a look?

**Comment by maleck13** [comment]
Changes look good to me. Will wait on @tiffanynolan

**Comment by tiffanynolan** [comment]
@aidenkeating @maleck13 Looks good to me. Thanks for the quick turnaround!

**Pull request merged**
