### PR TITLE
causes permissions issue on servers

### PR DESCRIPTION
**Pull request by mfrances17**
The yarn.lock file causes permissions issues on openshift clusters and prevents the build from executing. It was previously removed, still appears to be causing the same issue.

yarn-lock-error

### CODE REVIEW

**Comment by pb82** [comment]
@mfrances17 it should be fixed with this commit: https://github.com/integr8ly/tutorial-web-app/pull/123/commits/6f80ba80db7e6ca3a75e18b8836385ab77c25116

could you try if it's now working please?

**Comment by pb82** [comment]
@mfrances17 was it the build from the `yes-no-buttons` branch (https://circleci.com/gh/integr8ly/tutorial-web-app/240)?

Because the fixing commit is not in that branch yet.

**Comment by pb82** [comment]
@dlabaj Ok, happy to take another look after the deadline.

**Comment by mfrances17** [comment]
> @mfrances17 was it the build from the `yes-no-buttons` branch (https://circleci.com/gh/integr8ly/tutorial-web-app/240)?
> 
> Because the fixing commit is not in that branch yet.

I'm not sure what you mean. The build on OpenShift points to master, and I kicked off the build after your commits were in. Previous builds were ok once we deleted the yarn.lock file. It failed this morning. It's probably not fixed.

**Comment by dlabaj** [comment]
@pb82 Thanks Peter that would be great.  Here's the issue I created https://github.com/integr8ly/tutorial-web-app/issues/126.  Not sure why it keeps happening.

**Comment by mfrances17** [comment]
Thanks @pb82... I'm sure we'll figure it out eventually. Let me know if you want me to take a look, too.

**Comment by pb82** [comment]
@mfrances17 Ah sorry, you're right we only create the images from master after merging. In that case it's strange because I could see a successful image build after my PR. Anyway, i'll try to figure it out once we have more time.

**Pull request merged**
